<?php

namespace xframe\validation;
/**
 * Test class for Digit.
 * Generated by PHPUnit on 2012-01-13 at 10:12:31.
 */
class DigitTest extends \PHPUnit_Framework_TestCase {

    public function testValidate() {
        $validator = new Digit(1, 100);
        $this->assertTrue($validator->validate(50));
        $this->assertTrue($validator->validate('50'));
        
        $validator = new Digit();
        $this->assertTrue($validator->validate('1'));
    }

    /**
     *@expectedException \xframe\validation\Exception
     */
    public function testOutOfRangeLow() {
        $validator = new Digit(1, 100);
        $validator->validate(0);
    }

    /**
     * @expectedException \xframe\validation\Exception
     */
    public function testOutOfRangeHigh() {
        $validator = new Digit(1, 100);
        $validator->validate(0);
    }

    /**
     * @expectedException \xframe\validation\Exception
     */
    public function testBadType() {
        $validator = new Digit();
        $validator->validate('A');
    }

}
